syntax = "proto3";
option java_multiple_files = true;
package mapservice;
option  java_package="mapserviceGRPC";


//------------------------------------------------------------------------------------
// Beginning of service routines
//------------------------------------------------------------------------------------

service mapservice{
  rpc getObjID (req_ID) returns (resJSON) {}
  rpc getObjBbox (req_Obj_bbox) returns(resJSON) {}
  rpc getAmenityPoint (req_amenity_point) returns (resJSON) {}
  rpc getUsage (req_use) returns (resJSON) {}
  rpc calcRoute (req_route) returns (resJSON) {}
  rpc getImage (req_image) returns (PNG_image) {}
}


//------------------------------------------------------------------------------------
// Helper messages
//------------------------------------------------------------------------------------
message Coordinate{
  double x = 1;
  double y = 2;
}
/*
message CRS{
  string  type = 1;
  map<string,string> properties = 2;
}
*/

//message Geometry{
//  string type = 1;
//  repeated Coordinate coords = 2;
//  //CRS crs = 3;
//}


//------------------------------------------------------------------------------------
// Beginning of requests
// In the following are the different Requests
//------------------------------------------------------------------------------------
message req_ID{
  int64 ID = 1;
  bool amenity = 2;
}

message req_Obj_bbox{
  string type = 1;
  Coordinate bbox_tl = 2;
  Coordinate bbox_br = 3;
  bool amenity = 4;
  uint64 take = 6;
  uint64 skip = 7;
}


message req_amenity_point{
  string type = 1;
  Coordinate point = 2;
  double dist = 3;
  uint64 take = 5;
  uint64 skip = 6;
}



message req_route {
  uint64 start_ID = 1;
  uint64 end_ID = 2;
  bool length = 3;
}

message req_use{
  Coordinate bbox_tl = 1;
  Coordinate bbox_br = 2;
}

message req_image{
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
  repeated string filters = 4;
}
//------------------------------------------------------------------------------------
// Beginning of responses
// In the following the responses
//------------------------------------------------------------------------------------
//message MapObjectRPC{
//  int64 ID = 1;
//  string name = 2;
//  map<string, string> tags = 3;
//  string type = 4;
//  Geometry geo = 5;
//  repeated int64 children = 6;
//  bool amenity = 7;
//}
//
//message res_ObjArea{
//  repeated MapObjectRPC Objects = 1;
//  uint64 total = 2;
//}

message resJSON{
  string JSON = 1;
}



message res_err {
  string error_msg = 1;
}

message PNG_image{
  bytes data= 1;
}

